### ISSUE TITLE
**Change the reporter pipeline configuration high-level hierarchy **:

### ISSUE THREAD

**Issue by balazskreith** [ObserveRTC/connector#4]
```yaml
meta: (all meta informations to manage the pipeline)
source: (the source for the pipeline)
decoder: (the decoder for the source)
transformations: (all possible transformations we can have to the reports)
buffer: (property to accumulate the reports)
sink: (the sink we dump the reports to)
```
